version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432" #default
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    ports:
      - "8001:80"
volumes:
  postgres_data: